default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aut_demo_development

test: &test
  <<: *default
  database: aut_demo_test

production:
  <<: *default
  database: aut_demo_production
  username: aut_demo
  password: <%= ENV['AUT_DEMO_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
